# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ensure light HF deps in case tests import them
          pip install transformers sentencepiece --no-cache-dir || true

      - name: Run tests
        env:
          PYTHONUNBUFFERED: "1"
          TOKENIZERS_PARALLELISM: "false"
        run: pytest -q --maxfail=1
