name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure lightweight runtime deps are present if tests import transformers
          pip install transformers sentencepiece --no-cache-dir || true

      - name: Run tests
        env:
          TOKENIZERS_PARALLELISM: "false"
        run: pytest -q --maxfail=1
